### ISSUE TITLE
object() takes no parameters

### ISSUE THREAD

**Issue by Almoullim** [plasmashadow/yql#3]
``` python
from yql import YRequest
import logging

log = logging.getLogger(__name__)

y = YRequest(table="html")
y.add_filter("url", "http://en.wikipedia.org/wiki/Yahoo")
response = y.json()
log.info(response)
```

---

```
Traceback (most recent call last):
  File "ex13-3.py", line 6, in <module>
    y = YRequest(table="html")
  File "/usr/lib/python3.5/site-packages/yql/api/_api_request.py", line 28, in __init__
    self.__yql = _YQLBuilder(self.__tablename)
  File "/usr/lib/python3.5/site-packages/yql/_builder.py", line 95, in __new__
    cls.__instance = super(_YQLBuilder, cls).__new__(cls, *args, **kwargs)
TypeError: object() takes no parameters
```

**Comment by sourcepirate** [comment]
i see you are trying to use in python 3.5 which is not supported currently . I will make appropriate changes to make it work.

**Comment by carlosscastro** [comment]
Hi! Are there any workarounds go get this working with Python 3.5? Otherwise I'll just use http. Thanks!

**Comment by sourcepirate** [comment]
Will do... Started working on it right now .  Thanks,
